[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.6.15", features = ["csr"] }
scamper-rs = { path = "../lang" }
web-sys = { version = "0.3.72", features = [
	"Storage",
	"CanvasRenderingContext2d",
] }
